spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.32.10:3306/mall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.32.10:8848
  application:
    name: mall-member

  redis:
    port: 6379
    host: 192.168.32.10
  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000

logging:
  level:
    com.aining.mall: debug

