spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.32.10:8848
    alicloud:

      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: mall-lan
  application:
    name: mall-third-party
server:
  port: 12000